include_guard(GLOBAL)

function(_dvs_read_pe_uint16 executable offset outputVariable)
    file(READ "${executable}" bytes OFFSET "${offset}" LIMIT 2 HEX)
    string(LENGTH "${bytes}" byteLength)
    if(NOT byteLength EQUAL 4)
        message(FATAL_ERROR "Could not read a 16-bit PE field from '${executable}'.")
    endif()
    string(SUBSTRING "${bytes}" 0 2 lowByte)
    string(SUBSTRING "${bytes}" 2 2 highByte)
    math(EXPR value "0x${highByte}${lowByte}")
    set(${outputVariable} "${value}" PARENT_SCOPE)
endfunction()

function(_dvs_read_pe_uint32 executable offset outputVariable)
    file(READ "${executable}" bytes OFFSET "${offset}" LIMIT 4 HEX)
    string(LENGTH "${bytes}" byteLength)
    if(NOT byteLength EQUAL 8)
        message(FATAL_ERROR "Could not read a 32-bit PE field from '${executable}'.")
    endif()
    string(SUBSTRING "${bytes}" 0 2 byte0)
    string(SUBSTRING "${bytes}" 2 2 byte1)
    string(SUBSTRING "${bytes}" 4 2 byte2)
    string(SUBSTRING "${bytes}" 6 2 byte3)
    math(EXPR value "0x${byte3}${byte2}${byte1}${byte0}")
    set(${outputVariable} "${value}" PARENT_SCOPE)
endfunction()

function(dvs_verify_pe_subsystem executable expectedSubsystem)
    if(NOT EXISTS "${executable}" OR IS_DIRECTORY "${executable}")
        message(FATAL_ERROR "PE executable is missing: ${executable}")
    endif()

    file(READ "${executable}" dosSignature LIMIT 2 HEX)
    string(TOUPPER "${dosSignature}" dosSignature)
    if(NOT dosSignature STREQUAL "4D5A")
        message(FATAL_ERROR "'${executable}' does not have an MZ executable header.")
    endif()

    _dvs_read_pe_uint32("${executable}" 60 peHeaderOffset)
    file(READ "${executable}" peSignature OFFSET "${peHeaderOffset}" LIMIT 4 HEX)
    string(TOUPPER "${peSignature}" peSignature)
    if(NOT peSignature STREQUAL "50450000")
        message(FATAL_ERROR "'${executable}' does not have a valid PE signature.")
    endif()

    math(EXPR optionalHeaderOffset "${peHeaderOffset} + 24")
    _dvs_read_pe_uint16("${executable}" "${optionalHeaderOffset}" optionalHeaderMagic)
    if(NOT optionalHeaderMagic EQUAL 267 AND NOT optionalHeaderMagic EQUAL 523)
        message(FATAL_ERROR "'${executable}' has an unsupported PE optional header.")
    endif()

    if(expectedSubsystem STREQUAL "WINDOWS_GUI")
        set(expectedValue 2)
    elseif(expectedSubsystem STREQUAL "WINDOWS_CUI")
        set(expectedValue 3)
    else()
        message(FATAL_ERROR "Unknown expected PE subsystem: ${expectedSubsystem}")
    endif()

    math(EXPR subsystemOffset "${optionalHeaderOffset} + 68")
    _dvs_read_pe_uint16("${executable}" "${subsystemOffset}" actualValue)
    if(NOT actualValue EQUAL expectedValue)
        message(
            FATAL_ERROR
            "'${executable}' has PE subsystem ${actualValue}; expected ${expectedValue} "
            "(${expectedSubsystem})."
        )
    endif()
endfunction()

if(DEFINED DVS_PE_EXECUTABLE OR DEFINED DVS_PE_EXPECTED_SUBSYSTEM)
    if(NOT DEFINED DVS_PE_EXECUTABLE OR NOT DEFINED DVS_PE_EXPECTED_SUBSYSTEM)
        message(FATAL_ERROR "Both DVS_PE_EXECUTABLE and DVS_PE_EXPECTED_SUBSYSTEM are required.")
    endif()
    dvs_verify_pe_subsystem("${DVS_PE_EXECUTABLE}" "${DVS_PE_EXPECTED_SUBSYSTEM}")
endif()
